import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <header className="bg-red-300 p-4">
          <p>Header</p>
        </header>
        {children}
        <footer className="bg-slate-500 p-4">
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
